### ISSUE TITLE
Block unknown funding nodes

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin-discovery-server#6]
Block any funding node offer from unknown users.

**Comment by deaoja** [comment]
Temporary limitation in the current state when we have single funding node. All other funding nodes are not allowed as there is no trust evaluation criteria at the moment. Just the one is allowed.

DONE CRITERIA: 
- there is one single funding node to pair with
- it is not possible for anyone else to pair with discovery service trying to be a funding node
